version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: cargo
    directory: '/mysql-based/r2d2-based/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      mysql-r2d2:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: '/mysql-based/r2d2-based/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      mysql-r2d2-docker:
        patterns:
          - '*'


  - package-ecosystem: cargo
    directory: '/mysql-based/sqlx-based/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      mysql-r2d2:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: '/mysql-based/sqlx-based/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      mysql-r2d2-docker:
        patterns:
          - '*'
