services:
  mysql:
    image: mysql:latest
    container_name: mysql-r2d2
    environment: 
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --transaction-isolation=READ-COMMITTED
    ports:
      - 3306:3306
      - 33060:33060
      - 33062:33062
    volumes:
      - db-data-r2d2:/var/lib/mysql
      - ./db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-r2d2

  api:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    container_name: rust-mysq-api-r2d2
    environment:
      DATABASE_URL: mysql://mysql:mysql@mysql:3306/test
      RUST_LOG: info
    links:
      - mysql
    ports:
      - 3000:3000
    networks:
      - mysql-r2d2

networks:
  mysql-r2d2:
    name: mysql-r2d2

volumes:
  db-data-r2d2:
    driver: local
